import { config as loadDotenv } from 'dotenv';
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const ENV_KEYS = [
  'SENDGRID_API_KEY',
  'EMAIL',
  'MJ_APIKEY_PUBLIC',
  'MJ_APIKEY_PRIVATE',
  'MAILJET_APIKEY_PUBLIC',
  'MAILJET_APIKEY_PRIVATE',
  'EMAIL_PUPLIC_KEY',
  'EMAIL_PRIVATE_KEY',
  'APP_URL',
] as const;

loadDotenv({ path: resolve(ROOT, '.env') });

const lines = ENV_KEYS.flatMap((key) => {
  const value = String(process.env[key] || '').trim();
  return value ? [`${key}=${value}`] : [];
});

if (!lines.length) {
  console.error('No email-related variables found in .env. Copy .dev.vars.example to .dev.vars and fill in values.');
  process.exit(1);
}

const targetPath = resolve(ROOT, '.dev.vars');
const header = '# Generated by npm run sync:dev-vars — do not commit\n';
const body = `${header}${lines.join('\n')}\n`;

if (existsSync(targetPath)) {
  const existing = await readFile(targetPath, 'utf8');
  if (existing === body) {
    console.log('.dev.vars is already up to date.');
    process.exit(0);
  }
}

await writeFile(targetPath, body, 'utf8');
console.log(`Wrote ${lines.length} email variable(s) to .dev.vars`);
